name: Resolve pack downloads

on:
  workflow_call:
    inputs:
      side:
        description: Side to resolve (client, server, or both)
        required: false
        type: string
        default: both

permissions:
  contents: read

jobs:
  resolve:
    name: Pack downloads
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up dependencies
        uses: bertie-mc/bertie-ci/actions/setup@v3.7.0

      - name: Resolve pack downloads
        uses: bertie-mc/bertie-ci/actions/pack-resolve@v3.7.0
        with:
          side: ${{ inputs.side }}
