name: Export client pack

on:
  workflow_call:
    inputs:
      output-file:
        description: Output .mrpack filename
        required: true
        type: string
      artifact-name:
        description: Uploaded artifact name
        required: true
        type: string

permissions:
  contents: read

jobs:
  export:
    name: Export client pack
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up dependencies
        uses: bertie-mc/bertie-ci/actions/setup-nix@v3.4.0

      - name: Export client pack
        uses: bertie-mc/bertie-ci/actions/pack-export-client@v3.4.0
        with:
          output: .bertie-ci/export/${{ inputs.output-file }}

      - name: Upload client pack
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.artifact-name }}
          path: .bertie-ci/export/${{ inputs.output-file }}
          if-no-files-found: error
