name: Validate packwiz pack

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    name: Pack integrity
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up dependencies
        uses: bertie-mc/bertie-ci/actions/setup@v3.6.1

      - name: Validate pack
        uses: bertie-mc/bertie-ci/actions/pack-validate@v3.6.1
